### ISSUE TITLE
Duplicate YAML key MYSQL_ROOT_PASSWORD in 03-todo-web-application-mysql/docker-compose.yml

### ISSUE THREAD

**Issue by blackr1234** [in28minutes/kubernetes-crash-course#4]
```yaml
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: dummypassword 
```

There are two `MYSQL_ROOT_PASSWORD`.
